## Numpy intoduction

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

The main numpy structure is a multi-dimensional array which created from our dataset.

### Create numpy array

In [1]:
import numpy as np
numpy_array = np.array([1, 2, 3, 4], dtype=np.int64)  ## create int numpy array from list
numpy_array

array([1, 2, 3, 4], dtype=int64)

In [2]:
numpy_array.dtype # type of data from our array

dtype('int64')

In [3]:
numpy_array.shape # return all axes shape from out array

(4,)

In [4]:
numpy_array_two = np.array([[2, 3, 4], [5, 6, 7]]) # create two-dimentional numpy array from two lists
numpy_array_two

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
numpy_array_two.shape # return all axes shape from out array

(2, 3)

In [6]:
numpy_ones_array = np.ones(7) # create ones 7-dimensional numpy array
numpy_ones_array

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
numpy_zeros_array = np.zeros(2) # create zeros 2-dimendional numpy array
numpy_zeros_array

array([0., 0.])

In [8]:
numpy_identity_matrix = np.eye(6) # create identity matrix 6 x 6
numpy_identity_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
numpy_random_array = np.random.random((2, 3)) # create random numpy array 2 x 3
numpy_random_array

array([[0.44563744, 0.60801885, 0.47758424],
       [0.52486137, 0.87756076, 0.43235482]])

### Numpy values extraction

In [13]:
numpy_array[0]

1

In [14]:
numpy_array[1]

2

In [15]:
numpy_matrix = np.array([[1, 3, 4, 4], [2, 3, 4, 56]])
numpy_matrix

array([[ 1,  3,  4,  4],
       [ 2,  3,  4, 56]])

In [20]:
numpy_matrix[1, 3] # exctract element from 2th row and 4th column

56

In [21]:
numpy_matrix[:, :3] # exctract element from two rows and 0-3th columns

array([[1, 3, 4],
       [2, 3, 4]])

### Numpy values сonditional extraction

In [23]:
numpy_matrix > 2 ## firstly, create condition (conditional mask returned)

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [24]:
numpy_matrix[numpy_matrix > 2] # extract values which are more than 2 

array([ 3,  4,  4,  3,  4, 56])

### Shape and dimension change

In [26]:
numpy_matrix_two = np.array([[1, 3, 4, 4, 5], [2, 3, 4, 56, 5]])
numpy_matrix_two

array([[ 1,  3,  4,  4,  5],
       [ 2,  3,  4, 56,  5]])

In [27]:
numpy_matrix_two.shape

(2, 5)

In [28]:
numpy_matrix_two.flatten()   # change matrix to one-dimentional numpy array

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [29]:
numpy_matrix_two.T # matrix transpose

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

In [31]:
numpy_matrix_two.reshape((10,1)) # change matrix dimention to 10 x 1 

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [34]:
numpy_matrix_two.resize((10, 1)) # change source matrix dimention to 10 x 1 
numpy_matrix_two

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

### Math numpy operations

In [37]:
v = np.array([9, 10]) # first vector
w = np.array([11, 12]) # second vector

In [38]:
# Vector addition №1
v + w

array([20, 22])

In [39]:
# Vector addition №2
np.add(v, w)

array([20, 22])

In [40]:
# Vector subtraction №1
v - w

array([-2, -2])

In [42]:
# Vector subtraction №2
np.subtract(v, w)

array([-2, -2])

In [43]:
# Vector multiplication #1
v * w

array([ 99, 120])

In [44]:
# Vector multiplication #2
np.multiply(v, w)

array([ 99, 120])

In [45]:
# Scalar muliplication
np.dot(v, w)

219